# Generated by Django 4.1.5 on 2023-01-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Debit', 'Debit'), ('Credit', 'Credit'), ('Check', 'Check'), ('Trasnfer', 'Trasnfer')], max_length=10)),
            ],
        ),
    ]
