# Generated by Django 4.1.5 on 2023-01-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('debit', 'debit'), ('credit', 'credit'), ('check', 'check'), ('crasnfer', 'crasnfer')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
