# Generated by Django 4.1.5 on 2023-01-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_alter_client_address_and_more'),
        ('orders', '0002_order_delete_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Fecha de pedido'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Debito', 'Débito'), ('Crédito', 'Crédito'), ('Cheque', 'Cheque'), ('Transferencia', 'Transferencia')], max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=100, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.FloatField(verbose_name='Cantidad'),
        ),
    ]
