# Generated by Django 4.1.5 on 2023-01-20 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_number',
        ),
    ]
