# Generated by Django 4.1.5 on 2023-01-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=40, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=40, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=40, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='kind',
            field=models.CharField(choices=[('Revendedor/a', 'Revendedor/a'), ('Cliente', 'Cliente')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
