# Generated by Django 4.1.5 on 2023-01-22 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_condition_client_cuit_client_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{11}$', 'CUIT inválido.')], verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{8}$', 'DNI inválido.')], verbose_name='DNI'),
        ),
    ]
