# Generated by Django 4.1.5 on 2023-01-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_cuit_alter_client_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='condition',
            field=models.CharField(blank=True, choices=[('Consumidor final', 'Consumidor final'), ('Responsable inscripto', 'Responsable inscripto'), ('Iva exento', 'Iva exento')], max_length=50, verbose_name='Condición'),
        ),
    ]
