# Generated by Django 4.1.5 on 2023-01-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, verbose_name='Código')),
                ('description', models.CharField(max_length=85, verbose_name='Descripción')),
                ('tc2', models.CharField(max_length=4, verbose_name='TC2')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('stock', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
