# Generated by Django 4.1.5 on 2023-01-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=85)),
                ('tc', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
    ]
