# Generated by Django 4.1.5 on 2023-02-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Código')),
                ('description', models.CharField(max_length=85, verbose_name='Descripción')),
                ('tc', models.CharField(choices=[('Vulcano tc1', 'Vulcano tc1'), ('Vulcano tc2', 'Vulcano tc2'), ('Makkintal', 'Makkintal'), ('Moldear', 'Moldear'), ('LCI', 'LCI'), ('Ecopools', 'Ecopools')], max_length=20, null=True, verbose_name='Tipo de cambio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
