# Generated by Django 4.1.5 on 2023-01-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
