# Generated by Django 4.1.5 on 2023-01-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tc',
            field=models.CharField(choices=[('Vulcano tc1', 'Vulcano tc1'), ('Vulcano tc2', 'Vulcano tc2'), ('Makkintal', 'Makkintal'), ('Moldear', 'Moldear'), ('LCI', 'LCI'), ('Ecopools', 'Ecopools')], max_length=20, verbose_name='Tipo de cambio'),
        ),
    ]
