# Generated by Django 4.1.5 on 2023-01-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='tc',
            new_name='tc2',
        ),
    ]
