# Generated by Django 4.1.5 on 2023-01-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_tc_products_tc2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='code',
            new_name='Code',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='stock',
            new_name='Stock',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='tc2',
            new_name='TC2',
        ),
    ]
