# Generated by Django 4.1.5 on 2023-01-09 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_code_products_code_and_more'),
    ]

    
