# Generated by Django 4.1.5 on 2023-01-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_products_stock_alter_products_tc2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='products',
            name='TC2',
        ),
    ]
