# Generated by Django 4.1.5 on 2023-01-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(max_length=100, verbose_name='Número de teléfono')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Archivo adjunto')),
                ('query', models.TextField(max_length=500, verbose_name='¿En qué podemos ayudarte?')),
            ],
        ),
    ]
